var anObject = new Object();
var aString = new String();
var anArray = new Array();
var aNumber = new Number();
var aBoolean = new Boolean();
var aFunction = new Function();
console.log('value of anObject: ', anObject);
console.log('typeof anObject: ', typeof anObject);
console.log('value of aString: ', aString);
console.log('type of aString: ', typeof aString);
console.log('value of anArray: ', anArray);
console.log('type of anArray:', typeof anArray);
console.log('value of aNumber: ', aNumber);
console.log('type of aNumber: ', typeof aNumber);
console.log('value of aBoolean: ', aBoolean);
console.log('type of aBoolean: ', typeof aBoolean);
console.log('value of aFunction: ', aFunction);
console.log('typeof aFunction: ', typeof aFunction);
